#!/bin/bash

[[ -n $(lsmod | egrep "^v4l2loopback_dc") ]] && sudo rmmod v4l2loopback_dc
[[ -n $(lsmod | egrep "^v4l2loopback c") ]] && sudo rmmod v4l2loopback
sudo modprobe v4l2loopback devices=1 max_buffers=2 exclusive_caps=1 card_label="VirtualCam1"
sudo modprobe v4l2loopback_dc width=640 height=480 devices=2 max_buffers=2 exclusive_caps=1 card_label="VirtualCam"

