#!/bin/bash
#trayer --edge top --align right --transparent true --heighttype request --height 17 --widthtype pixel --width 47 --tint 0x282828
trayer --edge top --align right --transparent true --alpha 0 --heighttype pixel --height 14 --widthtype pixel --width 54 --tint 0x282828 
